apiVersion: batch/v1
kind: Job
metadata:
  name: {{PIPELINE_NAME}}-job
spec:
  template:
    metadata:
      labels:
        app: {{PIPELINE_NAME}}-job
    spec:
      containers:
        - name: beam-{{PIPELINE_NAME}}-job
          image: pypelines-beam-harness:2.56
          command: ["python"]
          args:
            - "app/{{PIPELINE_FILE_PATH}}"
            - "--deploy"
            - "--runner=FlinkRunner"
            - "--flink_master={{PIPELINE_NAME}}-cluster-rest:8081"
            - "--job_name=beam-{{PIPELINE_NAME}}"
            - "--streaming"
            - "--parallelism=3"
            - "--flink_submit_uber_jar"
            - "--environment_type=EXTERNAL"
            - "--environment_config=localhost:50000"
            - "--checkpointing_interval=10000"
      restartPolicy: Never